export const Actions = {
  superadmin: {
    crm_questions: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    guilds: { read: 'read' },
    auth: {
      read: 'read',
      read_me: 'read.me',
      create: 'create',
      create_keycloakAccount: 'create.keycloakAccount',
      delete: 'delete',
    },
    tm_trainees: {
      read: 'read',
      read_comment: 'read.comment',
      create_comment: 'create.comment',
      update: 'update',
      update_comment: 'update.comment',
      delete: 'delete',
    },
    crm_mentors: { manage: 'manage' },
    crm_admin_students: { manage: 'manage' },
    crm_audio_answers: { manage: 'manage' },
    companies: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    support_subscription: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    crm_roadmap: { manage: 'manage' },
    crm_payments_stats: { manage: 'manage' },
    tm_migrations: { run: 'run' },
    interview_sessions: {
      read: 'read',
      invite: 'invite',
      start: 'start',
      stop: 'stop',
      notCame: 'notCame',
      reject: 'reject',
      unban: 'unban',
    },
    courses: { create: 'create', update: 'update', manage: 'manage', read: 'read' },
    cities: {
      read: 'read',
      create: 'create',
      create_chat: 'create.chat',
      update: 'update',
      manage: 'manage',
    },
    tm_technologies: { read: 'read' },
    streams: {
      read_all: 'read.all',
      create: 'create',
      create_zoomsMeetings: 'create.zoomsMeetings',
      update: 'update',
      update_all: 'update.all',
      update_hiddenStatus: 'update.hiddenStatus',
      update_link: 'update.link',
      update_samuraiHubLessonId: 'update.samuraiHubLessonId',
      start: 'start',
      start_all: 'start.all',
      stop: 'stop',
      stop_all: 'stop.all',
      manage: 'manage',
      read: 'read',
    },
    countries: {
      read: 'read',
      read_stats: 'read.stats',
      create: 'create',
      create_chat: 'create.chat',
      update: 'update',
      manage: 'manage',
    },
    users: {
      read: 'read',
      create: 'create',
      update: 'update',
      update_all: 'update.all',
      manage: 'manage',
    },
    technologies: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    students_reports: { read: 'read', create: 'create', delete: 'delete' },
    labs: {
      read: 'read',
      create_binding: 'create.binding',
      create_studentLink: 'create.studentLink',
      delete_binding: 'delete.binding',
    },
    interviewer_settings: {
      manage: 'manage',
      read: 'read',
      read_truncatedVersion: 'read.truncatedVersion',
      create: 'create',
      update: 'update',
    },
    students_summaries: { read: 'read', create: 'create', update: 'update' },
    crm_video_answers: { manage: 'manage' },
    crm_support_statistics: { manage: 'manage' },
    student_notes: {
      read: 'read',
      create: 'create',
      read_files: 'read.files',
      create_file: 'create.file',
      update: 'update',
      manage: 'manage',
    },
    lessons: { manage: 'manage', read: 'read', create: 'create', update: 'update' },
    interview_feedbacks: {
      read: 'read',
      read_aboutInterviewerByStudents: 'read.aboutInterviewerByStudents',
      create: 'create',
      update: 'update',
      manage: 'manage',
    },
    support_queue_items: { read: 'read', create: 'create', update: 'update' },
    crm_interview_panel: { manage: 'manage' },
    crm_teams_panel: { manage: 'manage' },
    roles: { read: 'read', create: 'create', update: 'update', generate: 'generate' },
    crm_admin: {
      manage: 'manage',
      manage_devLogs: 'manage.devLogs',
      manage_exams: 'manage.exams',
      manage_playlists: 'manage.playlists',
      manage_sandbox: 'manage.sandbox',
      manage_zoomAccounts: 'manage.zoomAccounts',
    },
    students: {
      read: 'read',
      read_coursesBindings: 'read.coursesBindings',
      create: 'create',
      create_courseBindings: 'create.courseBindings',
      create_mentorship: 'create.mentorship',
      create_initPayments: 'create.initPayments',
      update: 'update',
      update_coursesBindings: 'update.coursesBindings',
      delete_coursesBindings: 'delete.coursesBindings',
      delete_mentorship: 'delete.mentorship',
      manage: 'manage',
    },
    tm_teams: {
      read: 'read',
      read_level: 'read.level',
      read_comment: 'read.comment',
      read_all: 'read.all',
      create: 'create',
      create_comment: 'create.comment',
      update: 'update',
      update_level: 'update.level',
      update_comment: 'update.comment',
      generate: 'generate',
      read_projects: 'read.projects',
      delete_member: 'delete.member',
      delete_project: 'delete.project',
    },
    interview_queue_items: {
      read: 'read',
      read_interviewed: 'read.interviewed',
      create_inviteAll: 'create.inviteAll',
      update: 'update',
      manage: 'manage',
    },
    crm_admin_lessons: {
      read: 'read',
      read_all: 'read.all',
      create: 'create',
      update: 'update',
      update_all: 'update.all',
      delete: 'delete',
      manage: 'manage',
    },
    streams_sessions: { read: 'read' },
    crm_initial_payments: { manage: 'manage' },
    mentor_labs: {
      notificate_studentInfo: 'notificate.studentInfo',
      notificate_userInfo: 'notificate.userInfo',
      notificate_badPhoto: 'notificate.badPhoto',
    },
    course_settings: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    respects: { read: 'read', manage: 'manage' },
    mentor_about_student_feedback: {
      read: 'read',
      read_all: 'read.all',
      update: 'update',
      manage: 'manage',
    },
    groups: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    messenger_chats: {
      read: 'read',
      create: 'create',
      create_chatLessonBinding: 'create.chatLessonBinding',
      create_inviteLink: 'create.inviteLink',
      update: 'update',
      manage: 'manage',
    },
    employments: { read: 'read', create: 'create', update: 'update', manage: 'manage' },
    crm_payments: { manage: 'manage' },
    migrations_scripts: { execute: 'execute' },
    support_sessions: {
      read: 'read',
      create: 'create',
      update: 'update',
      update_mark: 'update.mark',
      update_changeUser: 'update.changeUser',
      update_averagingInvalidTimeSessions: 'update.averagingInvalidTimeSessions',
      manage: 'manage',
    },
  },
};
